salt_role: master # master/minion

# salt master 服务器的地址，minion使用，支持多个master
salt_master:
  - saltmaster.fdisk.cc
# master_publish_port: 4505 # 默认是4505
# master_ret_port: 4506 # 默认是4506

# file_roots 配置
file_roots:
  base:
    - /srv/salt/salt/base
  dev:
    - /srv/salt/salt/dev
  prod:
    - /srv/salt/salt/prod

# pillar_roots 配置
pillar_roots:
  base:
    - /srv/salt/pillar/base
  dev:
    - /srv/salt/pillar/dev
  prod:
    - /srv/salt/pillar/prod
# minion_id: <minion_id> # 使用每个机器的FQDN作为minion_id，不要设置该变量。

# 定义自定签发的hosts列表。
# autosign_hosts:
#   - "*.fdisk.cc"

# 是否仅显示差异（发生变化的ID）
state_output_diff: False
